Storybook html
emulsify-ds/emulsify-wordpress-theme pull request #13
Opened 2021-03-15 21:50 UTC by evanmwillhite

Comparable to https://github.com/emulsify-ds/emulsify-drupal/pull/198. See that story for details and testing instructions.

2021-03-23 19:17 UTC, abu-bah approved these changes
Looks great. I went through Storybook and everything looks nice and seems to be working perfectly.

2021-11-17 19:15 UTC, ModulesUnraveled requested changes

2021-11-17 19:15 UTC, ModulesUnraveled commented on .browserslistrc
>  ie 11
I think we can remove ie11 now. We've removed it from most other projects

2022-03-10 20:02 UTC, amazingrando commented
@mikeethedude What is your status with this? Thanks!

2023-06-09 14:06 UTC, closed without merging